### ISSUE TITLE
策略具体是哪些

### ISSUE THREAD

**Issue by shellsec** [sorry510/go_binance_futures#1]
网格、马丁？

**Comment by HaoZhengZhao** [comment]
一般是长线穿越短线，加上整体的趋势判断等，很难简单描述清楚，需要阅读代码

**Comment by sorry510** [comment]
主要是长线穿短线形成金叉，加上整体的趋势判断和其它各种其他判定等，很难简单描述清楚，需要阅读代码

- 配置如下

```
# 购买策略(目前可以写 line1, line2, line3, line4)
strategy_trade = line4
# 选币策略(目前可以写 coin1, coin2, coin3, coin4)
strategy_coin = coin4
```

-  交易策略看 `feature/strategy` 目录源码

**Comment by prynnekey** [comment]
hello @shellsec ， https://github.com/shellsec/safeline2aodun 这个仓库里面包含一些敏感的信息，方便删除吗
