### ISSUE TITLE
后面啥时候可以自己写策略

### ISSUE THREAD

**Issue by wozaiwakuang** [sorry510/go_binance_futures#10]

**Comment by sorry510** [comment]
目前有点难度，需要实现 `feature/strategy/line_Interface.go` 接口, 具体就是参考 `feature/strategy/line/line7.go` 文件，写好后需要自己重新编译程序

后面可能会重新写，目前这个接口不够完善，能利用的东西太少了

**Comment by wozaiwakuang** [comment]
嗯,后续更新就快了,能把接口的指标放出来处理就能灵活很多了,老铁加油

**Comment by wozaiwakuang** [comment]
看看能集成几个常用的指标不

**Comment by wozaiwakuang** [comment]
合约交易中,价格显示的小数点看能显示 到后8位不? 监听哪点也整个价格的显示

**Comment by wozaiwakuang** [comment]
然后在监听技术类型哪点选择的类型有问题,怎么选择都是肯特通道

**Comment by sorry510** [comment]
1. 我就做了一个肯纳特通道的指标(看币安的肥猫的文章，自己理解写的)
2. 币本位的接口代码里面都没有去对接过，所以目前不会有

**Comment by wozaiwakuang** [comment]
肥猫的传说听过,没见过哈哈,
代码中是有币本位的接口?
大佬你都关注什么币种?

**Comment by sorry510** [comment]
币安广场搜索 肥猫，他的置顶文章就是 kc 通道的设定方法

代码目前没有币本位的接口

不是大佬，是韭菜，关注的山寨: ftt， fida，edu，ens
