### ISSUE TITLE
资金的汇率咱们能单独的监控不或者合约币种的给个显示

### ISSUE THREAD

**Issue by wozaiwakuang** [sorry510/go_binance_futures#11]

**Comment by sorry510** [comment]
这个比较简单，有空可以弄一下

**Comment by wozaiwakuang** [comment]
合约交易这个栏目是更具选币的策略筛选出来的吗?

**Comment by sorry510** [comment]
不是，这个列表的数据是当前币安所有可以交易的 usdt 交易对的币种(会自动更新)，选币的策略是从开关开启的币种里面进行自动的筛选

**Comment by wozaiwakuang** [comment]
好的,后面就等你基本完善了开搞了,币币合约,这个后面也会添加上来的的不?
我们做好币安得,在接入一个OKX得就完美了,挺实用的软件

**Comment by wozaiwakuang** [comment]
合约交易的当前的价格应该是不对的

**Comment by sorry510** [comment]
没问题的，只是有延迟，因为30秒轮询一次请求，设置这么慢的原因是因为刷新价格会影响同步修改数据

**Comment by wozaiwakuang** [comment]
这个价格是当前周期的收盘价格还是,实时的价格?

**Comment by wozaiwakuang** [comment]
实时价格,我观察了一会,是没有对的,价格的小数点看能自定义的控制位数不

**Comment by wozaiwakuang** [comment]
嗯,那你还是挺有耐心的,,APE你去抢购了没?这波赚了

**Comment by sorry510** [comment]
一直在写代码，哪有功夫去看盘，合约列表页面的价格精度修正好了，刷新频率可以自定义了

**Comment by wozaiwakuang** [comment]
你这个系统就是我想要的,当时我PYthon + ccxt 准备搞合约的,接码能力太差了,放弃了

**Comment by sorry510** [comment]
ape 怎么是新币呢，不是好久了吗，doge 我不看好，现在市值第 8，我看张不了多少

**Comment by wozaiwakuang** [comment]
doge耐不住他有个好爹码,时不时的奶一口,现在好的币种就BTC ETH BNB 我们玩不起啊,再就是SOL,我在手动操作币本位合约,

**Comment by wozaiwakuang** [comment]
广撒网的就是MEME的品种,也是要机器人的,

**Comment by wozaiwakuang** [comment]
对了你的windows的压缩包里面有个 linux_amd64_feature.tar.gz  有用?

**Comment by wozaiwakuang** [comment]
合约资金费率变化  我个人觉得你可以搞个指定的监控,这个汇率怎么吃我还没有研究过,有人在专门做这个业务

**Comment by wozaiwakuang** [comment]
timeout of 5000ms exceeded  会爆这个错误

**Comment by sorry510** [comment]
改了一下，前端删除了自定义的 tab 切换，因为会自带缓存，导致 api 请求过多，又是会超时报错
