### ISSUE TITLE
我试了一下，设置了止盈10%，但是到了10%也没止盈，这个页面也没显示收益比

### ISSUE THREAD

**Issue by gdmec07150942** [sorry510/go_binance_futures#4]
<img width="1231" alt="image" src="https://github.com/sorry510/go_binance_futures/assets/22065379/66ce2ee8-ffeb-4942-bb32-dc8d499db8c6">
<img width="581" alt="image" src="https://github.com/sorry510/go_binance_futures/assets/22065379/a003b1bd-b052-45d2-b7ec-4810c54a5d9f">
麻烦作者大大看下哈

**Comment by sorry510** [comment]
@gdmec07150942 这个现在，每个币种有单独的止盈和止损，全局的不会生效
<img width="1277" alt="image" src="https://github.com/sorry510/go_binance_futures/assets/19152210/a9dbfa10-7445-46a4-9121-31ef89db6fcb">
