### ISSUE TITLE
无法挂单

### ISSUE THREAD

**Issue by Reallymine** [sorry510/go_binance_futures#6]
您好！我启用程序之后出现这种问题。
![Uploading IMG_9838.PNG.jpg…]()

**Comment by Reallymine** [comment]
![IMG_9838 PNG](https://github.com/user-attachments/assets/4f96cfaa-29b0-4951-9a13-eadf992f8a02)

**Comment by Reallymine** [comment]
博主可以加个好友吗？我有些策略想要实现一下

**Comment by Reallymine** [comment]
我的v 18655779636

**Comment by sorry510** [comment]
@Reallymine 我看了报错信息应该是你合约账户设置了单项持仓模式，需要修改为双向持仓模式，app设置如图，但我忘记修改的时候有什么限制了，可能是有持仓时不让改? 也可能没啥限制
<img width="360" alt="image" src="https://github.com/user-attachments/assets/567b6b3d-7f8b-415a-abe7-f3fcb5dbd4e1">
<img width="358" alt="image" src="https://github.com/user-attachments/assets/8216a645-9cd4-4ddc-a7fe-dad5e891aef3">
