### ISSUE TITLE
有别的联系方式吗?策略能记成指标吗?Talib?

### ISSUE THREAD

**Issue by wozaiwakuang** [sorry510/go_binance_futures#7]
有别的联系方式吗?策略能记成指标吗?Talib?

**Comment by Autumn1992** [comment]
> 有别的联系方式吗?策略能记成指标吗?Talib?
其实策略可以用tradingview的hook通知然后触发交易 这样不用自己开发交易策略

**Comment by Autumn1992** [comment]
tradingview很多指标 而且可以回测一段周期内该策略的收益

**Comment by wozaiwakuang** [comment]
tradingview 需要单一的开启,不好整,做做测试看表可以的,集成一下吗,挺好的,还有,新版本的不能启动,提示数据库问题

**Comment by wozaiwakuang** [comment]
方便给个联系方式不CCXT开合约没整明白

**Comment by sorry510** [comment]
有空时我看下如何集成 tradingview 的hook通知然后触发交易

**Comment by wozaiwakuang** [comment]
嗯,能自己写交易策略可以的减少很多麻烦,用他的图形触发交易信号不是太友好,我觉得你这个项目不要放弃,挺好的,抢新币,方案挺好的.看看怎么衍生一下

**Comment by wozaiwakuang** [comment]
就是现在这个项目中低频率的交易完全合适了,还有持币的交易

**Comment by wozaiwakuang** [comment]
C:\windows_amd64_feature>C:\windows_amd64_feature\windows_amd64_feature.exe
2024/08/29 17:16:51.693 [I] [main.go:35]  webIndex: zmkm
[ORM]2024/08/29 17:16:51 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2024/08/29 17:16:51.724 [I] [main.go:86]  自动合约交易开启: 1
2024/08/29 17:16:51.724 [I] [main.go:72]  更新币种交易精度和增加新币
2024/08/29 17:16:51.724 [I] [main.go:81]  websocket 自动更新币种最新价格
must have one register DataBase alias named `default`
goroutine 9 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:16 +0x13
github.com/beego/beego/v2/client/orm.(*modelCache).bootstrap(0x1990940)
        /home/runner/go/pkg/mod/github.com/beego/beego/v2@v2.1.0/client/orm/models.go:325 +0x20e
github.com/beego/beego/v2/client/orm.BootStrap(...)
        /home/runner/go/pkg/mod/github.com/beego/beego/v2@v2.1.0/client/orm/models_boot.go:39
github.com/beego/beego/v2/client/orm.NewOrm()
        /home/runner/go/pkg/mod/github.com/beego/beego/v2@v2.1.0/client/orm/orm.go:624 +0x1b
go_binance_futures/feature.GetAllSymbols()
        /home/runner/work/go_binance_futures/go_binance_futures/feature/feature.go:336 +0x28
go_binance_futures/feature.StartTrade()
        /home/runner/work/go_binance_futures/go_binance_futures/feature/feature.go:51 +0x25
main.main.func3()
        /home/runner/work/go_binance_futures/go_binance_futures/main.go:90 +0x13
created by main.main in goroutine 1
        /home/runner/work/go_binance_futures/go_binance_futures/main.go:88 +0xde
panic: <Ormer.Using> unknown db alias name `default`

goroutine 9 [running]:
github.com/beego/beego/v2/client/orm.NewOrmUsingDB({0x1376d5b, 0x7})
        /home/runner/go/pkg/mod/github.com/beego/beego/v2@v2.1.0/client/orm/orm.go:633 +0x93
github.com/beego/beego/v2/client/orm.NewOrm()
        /home/runner/go/pkg/mod/github.com/beego/beego/v2@v2.1.0/client/orm/orm.go:625 +0x2c
go_binance_futures/feature.GetAllSymbols()
        /home/runner/work/go_binance_futures/go_binance_futures/feature/feature.go:336 +0x28
go_binance_futures/feature.StartTrade()
        /home/runner/work/go_binance_futures/go_binance_futures/feature/feature.go:51 +0x25
main.main.func3()
        /home/runner/work/go_binance_futures/go_binance_futures/main.go:90 +0x13
created by main.main in goroutine 1
        /home/runner/work/go_binance_futures/go_binance_futures/main.go:88 +0xde

我这边的机器一直报这个错误,不知道是那一步错误了

**Comment by wozaiwakuang** [comment]
策略目录应该是打包打漏了

**Comment by sorry510** [comment]
@wozaiwakuang 
错误原因是 go 打包时，没有正确处理连接 sqlite3 数据库的依赖，window 下我没有测试过，我会尝试修改 workflow 修复这个打包问题

**Comment by wozaiwakuang** [comment]
@sorry510 嗯,到时一起聊聊策略

**Comment by wozaiwakuang** [comment]
@sorry510 这个项目不要放弃了啊,选币的列表可能要优化一下,看看后面支持一下代理IP不,本地能跑跑测试

**Comment by zghelp** [comment]
能支持一下tradeview就好了
